sudo: true
before_install:
    - sudo apt-get update && sudo apt-get install -y pass gnupg

language: go

go:
  - 1.6

matrix:
  fast_finish: true
  
script:
  - make vet
  - make lint
  - make
  - export GNUPGHOME=$(pwd)/t/.gnupg && export PASSWORD_STORE_DIR=$(pwd)/t/.password-store && export JIRACLOUD=1 && ./t/100basic.t -w -a 2>&1 
