# docker required for the tests (run via prove)
sudo: required
services:
  - docker

language: go

go:
  - 1.6

matrix:
  fast_finish: true
  
script:
  - make vet
  - make lint
  - make
  - export OSHT_VERBOSE=1 && prove -v

cache:
  directories:
    - t/.maven-cache
