sudo: true
before_install:
    - sudo apt-get update && sudo apt-get install -y libgnome-keyring-dev

language: go

go:
  - 1.6

matrix:
  fast_finish: true
  
script:
  - make vet
  - make lint
  - make
  - JIRACLOUD=1 ./t/100basic.t -w -a 2>&1 

cache:
  directories:
    - t/.maven-cache
