sudo: true
before_install:
    - sudo apt-get update && sudo apt-get install -y pass gnupg

language: go

go:
  - 1.6

matrix:
  fast_finish: true
  
script:
  - make vet
  - make lint
  - make
  - make prove 2>&1 
